name: "[uv] lint-and-test"

on:
  pull_request:

jobs:
  uv-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run pytest
        run: uv run --group dev pytest
